version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-leave
    restart: always
    ports:
      - "5413:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: new_employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-leave
    restart: always
    ports:
      - "3413:3413"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin321
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: new_employee_db

  frontend:
    build: ./Fronted
    container_name: frontend-service
    ports:
      - "8037:80"

  hr_page:
    build: ./HR_Page
    container_name: hrpage-service
    ports:
      - "8038:80"

volumes:
  pgdata:

